### ISSUE TITLE
Battery Details Issue in Settings

### ISSUE THREAD

**Issue by liutiao888888** [roothide/Bootstrap#221] opened 2024-01-22 15:01 UTC
### Device Model

iPhone14pm

### iOS Version

16.6.1

### Bootstrap Version

1.1

### What happened?

Battery Usage Details Cannot Be Loaded During Injection Settings

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment] 2024-01-22 17:25
Duplicate of #52

**Closed by dleovl** 2024-01-22 17:25 UTC
Labels: bug
