### ISSUE TITLE
Battery usage cannot be loaded when com.apple.Preferences is enabled in App List

### ISSUE THREAD

**Issue by ssdsl0126** [roothide/Bootstrap#52] opened 2024-01-04 08:20 UTC
After enabling the tweak, the configured battery settings fail to load properly
![image](https://github.com/RootHide/Bootstrap/assets/35905829/5261e4a3-92c7-46f1-a66d-bdce1b8472fe)

**Comment by dleovl** [comment] 2024-01-04 08:59
Bug confirmed A13 17.0 with injection into com.apple.Preferences. Possible duplicate of #26

**Comment by roothide** [comment] 2024-01-08 11:14
Known issue. 
temporarily disable tweak for Settings app.

**Comment by deepansharya1111** [comment] 2024-02-21 16:20
It used to show fine till a few weeks back as I remember. But now it’s just as this issue mentions.

**Comment by sanmiguel71** [comment] 2024-02-24 13:23
opa334 fixed the issue in Dopamine 2.0 already, maybe helpful for you:

https://github.com/opa334/Dopamine/issues/359#issuecomment-1961759549

https://github.com/opa334/Dopamine/commit/8f1cf9019fb365298a282d430502e2167f412139

**Comment by roothider** [comment] 2024-09-29 04:12
> opa334 fixed the issue in Dopamine 2.0 already, maybe helpful for you:
> 
> [opa334/Dopamine#359 (comment)](https://github.com/opa334/Dopamine/issues/359#issuecomment-1961759549)
> 
> [opa334/Dopamine@8f1cf90](https://github.com/opa334/Dopamine/commit/8f1cf9019fb365298a282d430502e2167f412139)

thats different issue, Bootstrap is not a jailbreak

**Comment by roothider** [comment] 2024-09-29 04:30
<img width="792" alt="image" src="https://github.com/user-attachments/assets/546aac82-2560-456c-8844-e657aab9b27c">

this issue is not fixable on Bootstrap

**Closed as not planned** 2024-09-30 10:04 UTC
Labels: bug, confirmed
