### ISSUE TITLE
Code (255) after status: Rebuilding apps

### ISSUE THREAD

**Issue by Baguette02** [roothide/Bootstrap#102] opened 2024-01-09 23:19 UTC
I am on ios 16.1.2 (iphone 13 pro)

after i click bootstrap  it goes through everything exept the last step it gives me an code 255 and does nothing. 

Sileo and zebra work but i cannot get into AppEnabler. (Also Serotonin does not work anymore.)

i tried rebooting,force rebooting reinstalling Bootstrap upgrading from 4.1 to 4.2 nothing worked.

![IMG_4264](https://github.com/roothide/Bootstrap/assets/156025655/be42691a-b200-4573-86c2-e660a14bea79)
![IMG_4262](https://github.com/roothide/Bootstrap/assets/156025655/90966d53-5fbf-4b26-8cca-b6f03eef3987)

**Comment by dleovl** [comment] 2024-01-09 23:46
Issue may be already known which will be fixed in beta 4.3

**Comment by roothide** [comment] 2024-01-10 03:17
this is because you did not disable tweak for all apps before uninstalling the old beta version. some apps still remain in the tweak-injected state. the new beta version has some bugs when dealing with old versions of tweak-injected apps, and we will fix this soon.

**Comment by truexcoin** [comment] 2024-01-10 03:32
how do you fix this

**Comment by dleovl** [comment] 2024-01-10 09:13
Possible duplicate of #95

**Comment by dleovl** [comment] 2024-01-21 09:58
Closing. If your issue persists on the latest version, please create a new issue.

**Closed by dleovl** 2024-01-21 09:58 UTC
Labels: bug
