### ISSUE TITLE
Battery drain & notifications issues

### ISSUE THREAD

**Issue by DIDIZ0MBIEX** [roothide/Bootstrap#109] opened 2024-01-10 15:26 UTC
Either bootstrap or serotonin is causing a massive battery drain 

Using app enabler stops notifications showing up in the notification settings and stops notification coming through for those apps

**Comment by dleovl** [comment] 2024-01-10 17:27
Battery drain can be attributed to `mineek/Serotonin`, there are no mass reports of battery drain with just the RootHide Bootstrap by itself.

Notifications, duplicate of #2.

**Closed by dleovl** 2024-01-10 17:27 UTC
