### ISSUE TITLE
Redirecting to enabled apps that are in AppEnabler

### ISSUE THREAD

**Issue by treasunew** [roothide/Bootstrap#130] opened 2024-01-16 03:55 UTC
Opening wi-fi setting from the cc, it will be redirected to TikTok.

**Comment by dleovl** [comment] 2024-01-16 06:44
1. What i(Pad)OS version are you running?
2. What device model are you using?
3. Are you using any SpringBoard tools such as Serotonin?
4. How can we reproduce this issue?

**Comment by treasunew** [comment] 2024-01-16 07:00
> * What i(Pad)OS version are you running?
> * What device model are you using?
> * Are you using any SpringBoard tools such as Serotonin?
> * How can we reproduce this issue?

Version: 16.6
Model: iPhone11
Environment: Yes, I’m using Serotonin
Issue Reproduction: just do the same as i do
- enable DouYin(TikTok of Chinese version) in Bootstrap’s AppEnabler
- install a tweak from [telegram](https://t.me/Backup_3toone/90)
- click WLAN setting in cc.
- it finally switch to DouYin instead of WLAN setting.

**Comment by dleovl** [comment] 2024-01-16 07:14
> > * What i(Pad)OS version are you running?
> > * What device model are you using?
> > * Are you using any SpringBoard tools such as Serotonin?
> > * How can we reproduce this issue?
> 
> Version: 16.6 Model: iPhone11 Environment: Yes, I’m using Serotonin Issue Reproduction: just do the same as i do
> 
> * enable DouYin(TikTok of Chinese version) in Bootstrap’s AppEnabler
> * install a tweak from [telegram](https://t.me/Backup_3toone/90)
> * click WLAN setting in cc.
> * it finally switches to DouYin instead of WLAN setting.

Could you upload the deb here directly (for those who don't have Telegram)? Also, can you verify this issue still occurs when you reboot and bootstrap but don't enable Serotonin?

**Comment by treasunew** [comment] 2024-01-16 07:19
> > > * What i(Pad)OS version are you running?
> > > * What device model are you using?
> > > * Are you using any SpringBoard tools such as Serotonin?
> > > * How can we reproduce this issue?
> > 
> > 
> > Version: 16.6 Model: iPhone11 Environment: Yes, I’m using Serotonin Issue Reproduction: just do the same as i do
> > 
> > * enable DouYin(TikTok of Chinese version) in Bootstrap’s AppEnabler
> > * install a tweak from [telegram](https://t.me/Backup_3toone/90)
> > * click WLAN setting in cc.
> > * it finally switches to DouYin instead of WLAN setting.
> 
> Could you upload the deb here directly (for those who don't have Telegram)? Also, can you verify this issue still occurs when you reboot and bootstrap but don't enable Serotonin?

i’ll try it now
here’s the deb
[DouYin_layer.zip](https://github.com/roothide/Bootstrap/files/13946638/DouYin_layer.zip)

**Comment by treasunew** [comment] 2024-01-16 07:25
> > > * What i(Pad)OS version are you running?
> > > * What device model are you using?
> > > * Are you using any SpringBoard tools such as Serotonin?
> > > * How can we reproduce this issue?
> > 
> > 
> > Version: 16.6 Model: iPhone11 Environment: Yes, I’m using Serotonin Issue Reproduction: just do the same as i do
> > 
> > * enable DouYin(TikTok of Chinese version) in Bootstrap’s AppEnabler
> > * install a tweak from [telegram](https://t.me/Backup_3toone/90)
> > * click WLAN setting in cc.
> > * it finally switches to DouYin instead of WLAN setting.
> 
> Could you upload the deb here directly (for those who don't have Telegram)? Also, can you verify this issue still occurs when you reboot and bootstrap but don't enable Serotonin?

It still occurred without Serotonin.

**Comment by treasunew** [comment] 2024-01-16 12:36
I found a more serious issue, all notifications are redirecting to DouYin if I click them.

**Comment by dleovl** [comment] 2024-01-21 09:59
Duplicate of #217

**Closed by dleovl** 2024-01-21 09:59 UTC
Labels: bug

**Comment by roothider** [comment] 2024-02-04 17:52
already fixed in 1.1.1

**Comment by treasunew** [comment] 2024-02-05 12:33
> already fixed in 1.1.1

greatly thanks for your efforts
