### ISSUE TITLE
'Wait for Fix' incompatibility for iOS 17.0 on A15+ devices

### ISSUE THREAD

**Issue by MysticalFlight** [RootHide/Bootstrap#17] opened 2023-12-29 22:11 UTC
Doesn’t work on iOS 15.6 and it says wait for fix so is the issue found already?
![D919A20A-0861-4F9A-9812-8973F96331E9](https://github.com/RootHide/Bootstrap/assets/153443347/2a9621df-b539-449d-8557-16a1c5c11a17)

**Comment by sanderDijkxhoorn** [comment] 2023-12-29 22:31
Multiple people are having this issue.

iOS 16.0.2 - 13 Pro Max
iOS 16.3.1 - 13

**Comment by jrapf32** [comment] 2023-12-29 22:36
iOS 16.0.3 - 10S

**Comment by cakarlen** [comment] 2023-12-29 23:18
Not working:

iPhone 14, iOS 16.1
iPhone 7+, iOS 14.0.1
iPhone X, iOS 15.3.1

**Comment by samojfsdofjs** [comment] 2023-12-29 23:18
since title got changed,

mine was iphone 12, 15.6

another person has same problem on:
iphone 13 pro, 16.4.1

**Comment by RUGMJ** [comment] 2023-12-29 23:19
iPhone 13 16.1

**Comment by GooglyBlox** [comment] 2023-12-29 23:19
iPhone 14 Pro, 16.1.2, same problem

**Comment by solikeididtheuh** [comment] 2023-12-29 23:21
Happening to me too. iPad air 3 (11,3) 16.4.1

**Comment by jrapf32** [comment] 2023-12-29 23:23
Found fix if you don't have A15 or A16 in Bootstrap/ViewController.m change self.bootstraBtn.enabled = NO in the if(WaitForFix) statement to self.bootstraBtn.enabled = YES; It works on Xs

**Comment by RUGMJ** [comment] 2023-12-29 23:24
so its intentional for A15+?

**Comment by jrapf32** [comment] 2023-12-29 23:24
yes look cpuFamily==CPUFAMILY_ARM_BLIZZARD_AVALANCHE || cpuFamily==CPUFAMILY_ARM_EVEREST_SAWTOOTH

**Comment by MysticalFlight** [comment] 2023-12-29 23:26
iPhone XS Max - ios 17
iphone 11 - ios 16.1
iphone 12 - 17.0

collected from roothide discord

**Comment by Imadedddin** [comment] 2023-12-29 23:27
Iphone 17 pro max 
Ios17 not working stuck at bootstraping

**Comment by dleovl** [comment] 2023-12-29 23:27
**Manually editing the source code puts your device at risk. Certain devices have incompatibilities for a reason. Only you are responsible for any damage you do to your devices.**

**Comment by Migaas001** [comment] 2023-12-29 23:35
iPhone 12 iOS 17 the same
![IMG_7258](https://github.com/RootHide/Bootstrap/assets/135570897/0d8caa5a-c251-407e-a13d-a791f9722638)

**Comment by hoaug-tran** [comment] 2023-12-29 23:39
iPhone XS Max - IOS 15.5

**Comment by Lorxxxxx** [comment] 2023-12-29 23:40
![CF81382A-F50D-4DF7-91B1-BAAAEF603BD9](https://github.com/RootHide/Bootstrap/assets/94084757/e87c5662-7751-4b00-8ac6-a96eb9d52ee5)

**Comment by Lorxxxxx** [comment] 2023-12-29 23:40
Iphone xr, ios 16.1.2
![04EA46FE-A6F3-46B1-A8F0-0FDD3DFCEF80](https://github.com/RootHide/Bootstrap/assets/94084757/95dfec63-e919-49c5-97ab-170a8a53457f)

**Comment by B1N0Lee** [comment] 2023-12-29 23:42
iPhone 14 Pro Max - IOS 16.4.1
Waiting for fix
![IMG_0308](https://github.com/RootHide/Bootstrap/assets/125391458/2eaf2ab6-e76f-46f3-bd04-4ab1a7c76271)

**Comment by justs1my0ung** [comment] 2023-12-29 23:45
ipad pro 11in 4th(14,3)
ios 16.4
wait for fix

**Comment by sanderDijkxhoorn** [comment] 2023-12-30 00:01
Issue has been fixed, pull the latest changes.

**Comment by dleovl** [comment] 2023-12-30 00:05
Refer to https://github.com/RootHide/Bootstrap/commit/ca880497179378695341c29b38796381c577e4bb

**Comment by Mackay8** [comment] 2023-12-30 00:07
Iphone12 ios16.2 crashed

**Comment by sanderDijkxhoorn** [comment] 2023-12-30 00:13
@dleovl why did you reopen the issue?

**Comment by dleovl** [comment] 2023-12-30 00:14
> @dleovl why did you reopen the issue?

https://github.com/RootHide/Bootstrap/commit/ca880497179378695341c29b38796381c577e4bb mentions there's still an incompatibility on iOS 17.0 for A15+ devices

**Comment by sanderDijkxhoorn** [comment] 2023-12-30 00:15
> > @dleovl why did you reopen the issue?
> 
> [ca88049](https://github.com/RootHide/Bootstrap/commit/ca880497179378695341c29b38796381c577e4bb) mentions there's still an incompatibility on iOS 17.0 for A15+ devices

That is not a bug but a feature haha

**Comment by RootHide** [comment] 2023-12-30 00:17
only 17.0 on A15+ still wait for fixing. bug fixed on other ios version/device.  try the latest commits.

**Comment by sanderDijkxhoorn** [comment] 2023-12-30 00:17
iOS 17.0 for A15+ still needs to be implemented.

The issue was originally created because a lot of device were detected as incompatible while they actually were compatible. Talked with the dev about this and resolved that issue.

**Closed by sanderDijkxhoorn** 2023-12-30 00:17 UTC
Labels: bug, help wanted
