### ISSUE TITLE
The battery charging situation will not load during the injection settings.

### ISSUE THREAD

**Issue by FengT0T** [roothide/Bootstrap#241] opened 2024-02-01 07:58 UTC
### Device Model

iPhone13mini A15

### iOS Version

16.5

### Bootstrap Version

1.1.1

### Serotonin Version

1.2.1

### What happened

In the bootstrap injection, the battery usage data will not be loaded. When the injection is cancelled, it will return to normal.

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by roothider** [comment] 2024-02-01 19:33
Known issue, the current solution is to temporarily disable tweaks for settings app

**Comment by dleovl** [comment] 2024-02-01 20:11
Duplicate of #52

**Closed by dleovl** 2024-02-01 20:11 UTC
Labels: bug
