### ISSUE TITLE
error(255) exception: AppEnabler.m (236) when enabling certain apps

### ISSUE THREAD

**Issue by m1337v** [roothide/Bootstrap#246] opened 2024-02-04 23:50 UTC
### Device Model

iPhone 12

### iOS Version

15.6

### Bootstrap Version

1.2 (compiled from latest source)

### What happened

When i try to enable tweaks for the apps Sparkasse (https://apps.apple.com/de/app/sparkasse-ihre-mobile-filiale/id320599923), PushTan (https://apps.apple.com/de/app/s-pushtan-f%C3%BCr-iphone-und-ipad/id563488727), Deutsche Bank Phototan (https://apps.apple.com/de/app/deutsche-bank-phototan/id937259592), DKB tan2go (https://apps.apple.com/de/app/dkb-tan2go/id881860044), norisbank phototan (https://apps.apple.com/de/app/norisbank-phototan/id937266156)
it fails with this error:

error(255)
...
assertion failed: (ordinal >0), function patch_macho, file exepatch.c, line 390.

***exception: AppEnabler.m (236)

For other apps it works as expected. Could it be decryption protection?

![IMG_6421](https://github.com/roothide/Bootstrap/assets/20713070/d6ca3196-9b57-4095-803e-2781a5e1818b)
![IMG_6422](https://github.com/roothide/Bootstrap/assets/20713070/fc082222-d8e2-4e16-b70e-eef5b09e6c11)
![IMG_6423](https://github.com/roothide/Bootstrap/assets/20713070/dcf003d9-cccc-4636-8c88-ef72415f91e9)

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by roothider** [comment] 2024-02-05 00:20
okay, confirmed. will be fixed in new version.

**Comment by dleovl** [comment] 2024-02-05 02:10
Does the error persist with 1.2.1?

**Comment by m1337v** [comment] 2024-02-05 12:38
@dleovl the error when enabling tweaks for the apps is fixed. The apps crash on launch now tho after tweaks are enabled. Thats probably due to jailbreak detection

**Comment by roothider** [comment] 2024-02-05 12:40
> @dleovl the error when enabling tweaks for the apps is fixed. The apps crash on launch now tho after tweaks are enabled. Thats probably due to jailbreak detection

Yes, since they are financial/banking apps

**Closed** 2024-02-06 00:36 UTC
Labels: bug, confirmed
