### ISSUE TITLE
Banking app issue

### ISSUE THREAD

**Issue by MysticallyQ8** [roothide/Bootstrap#234] opened 2024-01-25 11:00 UTC
### Device Model

iphone 14 pro max

### iOS Version

16.6.1

### Bootstrap Version

1.1

### Serotonin Version

1.2.1

### What happened?

Hello, i have recently encountered my banking app that detect my JB, iphone 14 pro max ios 16.6.1, i have been using the app without no bypass tweaks and it was fine for almost 2 weeks until yesterday it detected as My device is unsecured Bc of jailbreak. I followed the uninstallation method from A to Z and yet i still get the window saying “Device is unsecured”
![IMG_4510](https://github.com/roothide/Bootstrap/assets/130188733/282f58ca-ca1c-403d-a74f-85ac021a4d3a)

https://apps.apple.com/kw/app/gulf-bank-mobile-banking/id1577206679

^ this is the link to the app in appstore

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment] 2024-01-25 14:05
Duplicate of #48

**Closed by dleovl** 2024-01-25 14:05 UTC
Labels: bug

**Comment by MysticallyQ8** [comment] 2024-01-25 16:18
> Duplicate of #48

how it is a duplicate? i did your method and it did not work!

**Comment by dleovl** [comment] 2024-01-25 18:29
> > Duplicate of #48
> 
> how it is a duplicate? i did your method and it did not work!

The post is not a method. You write about your issue there and await testing/a response. This isn't perfect, so jailbreak detection will only clutter issues.
